version = 1

[[analyzers]]
name = "cxx"
enabled = true

[[analyzers]]
name = "cpplint"
enabled = true
config = """ 
  .cpplint
"""

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = "./Dockerfile"
