version = 1

[[analyzers]]
name = "cxx"
enabled = true

[[analyzers]]
name = "cpplint"
enabled = true
config = """ 
  .cpplint
"""

[[analyzers]]
name = "ninja"
enabled = true

[[analyzers]]
name = "cmake"
enabled = true
config = """
  -DCMAKE_CXX_FLAGS=-g -O0 -Wall -fprofile-arcs -std=c++11 -ftest-coverage -DCMAKE_BUILD_TYPE=Debug -Werror --coverage -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=../bin
  -DCMAKE_C_FLAGS=-g -O0 -Wall -W -fprofile-arcs -ftest-coverage -std=c++11 -DCMAKE_BUILD_TYPE=Debug --coverage -Werror -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=../bin
  -DCMAKE_EXE_LINKER_FLAGS=-fprofile-arcs -ftest-coverage
"""

[[analyzers]]
name = "test-coverage"
enabled = false

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = "./Dockerfile"
