version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.0.0
  python: circleci/python@2.1.1

parameters:
  os:
    type: string
    enum:
      - ubuntu
      - macos

workflows:
    jobs:
      - configrations:
          docker:
            - image: << parameters.os >>:latest
          steps:
            - checkout
            - path-filtering/filter:
                filters:
                  - filter-type: include
                    pattern: 'src/**'
                  - filter-type: include
                    pattern: 'CMakeLists.txt'
                  - filter-type: include
                    pattern: '.cpplint'
                  - filter-type: include
                    pattern: '.deepsource.toml'
                  - filter-type: include
                    pattern: 'bin/**'
                command: echo "export changes=true" >> $BASH_ENV

    build:
      - build:
          docker:
            - image: << parameters.os >>:latest
          steps:
            - checkout
            - python/dist
            name: Build
            command: |
              sudo apt-get update
              sudo apt-get install libcurl4-openssl-dev librpm-dev libapt-pkg-dev ninja-build
              pip install cpplint && mkdir -p build && cd build && rm -rf * && cmake .. -GNinja && ninja cpplint

    docker:
      docker:
        - images: << parameters.os >>:latest
      steps:
        
