name: CMake

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md' 
      - '*.MD'
      - '*ignore'
      - '.github/*'
      - '!.github/workflows/*'

  pull_request:
    branches: [ "master" ]
  workflow_run:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake ninja
      run: sudo apt install ninja-build -y |
        mkdir build
        cmake -GNinja build -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=../bin

    - name: Build
      run: cmake --build build

  #  - name: Test
  #    working-directory: ${{github.workspace}}/build
       # Execute tests defined by the CMake configuration.
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
  #    run: ctest -C ${{env.BUILD_TYPE}}

